# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertywin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(317, 601)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = CpPasteTable(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox_rownum = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_rownum.setMaximum(10000)
        self.spinBox_rownum.setObjectName("spinBox_rownum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_rownum)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_colnum = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_colnum.setMaximum(10000)
        self.spinBox_colnum.setObjectName("spinBox_colnum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_colnum)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.pushButtonOk = QtWidgets.QPushButton(Dialog)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.gridLayout.addWidget(self.pushButtonOk, 2, 0, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(Dialog)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "属性"))
        self.groupBox.setTitle(_translate("Dialog", "列标题设置"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "列号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "列标题"))
        self.groupBox_2.setTitle(_translate("Dialog", "其他设置"))
        self.label.setText(_translate("Dialog", "行数"))
        self.label_2.setText(_translate("Dialog", "列数"))
        self.pushButtonOk.setText(_translate("Dialog", "确认修改"))
        self.pushButton_reset.setText(_translate("Dialog", "重置"))
from PyLogicFile.CopyPasteTable import CpPasteTable
