# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_propertyDialog(object):
    def setupUi(self, propertyDialog):
        propertyDialog.setObjectName("propertyDialog")
        propertyDialog.resize(331, 390)
        self.gridLayout_3 = QtWidgets.QGridLayout(propertyDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(propertyDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_colTitle = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_colTitle.setObjectName("listWidget_colTitle")
        self.gridLayout.addWidget(self.listWidget_colTitle, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(propertyDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox_rownum = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_rownum.setObjectName("spinBox_rownum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_rownum)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox_colnum = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_colnum.setObjectName("spinBox_colnum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_colnum)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(propertyDialog)
        QtCore.QMetaObject.connectSlotsByName(propertyDialog)

    def retranslateUi(self, propertyDialog):
        _translate = QtCore.QCoreApplication.translate
        propertyDialog.setWindowTitle(_translate("propertyDialog", "属性"))
        self.groupBox.setTitle(_translate("propertyDialog", "列标题设置"))
        self.groupBox_2.setTitle(_translate("propertyDialog", "其他设置"))
        self.label.setText(_translate("propertyDialog", "行数"))
        self.label_2.setText(_translate("propertyDialog", "列数"))
