# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_propertyDialog(object):
    def setupUi(self, propertyDialog):
        propertyDialog.setObjectName("propertyDialog")
        propertyDialog.resize(362, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(propertyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(propertyDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_colTitle = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_colTitle.setObjectName("listWidget_colTitle")
        self.gridLayout.addWidget(self.listWidget_colTitle, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(propertyDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Labelrowcount = QtWidgets.QLabel(self.groupBox_2)
        self.Labelrowcount.setObjectName("Labelrowcount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Labelrowcount)
        self.LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Labelcolcount = QtWidgets.QLabel(self.groupBox_2)
        self.Labelcolcount.setObjectName("Labelcolcount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Labelcolcount)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(propertyDialog)
        QtCore.QMetaObject.connectSlotsByName(propertyDialog)

    def retranslateUi(self, propertyDialog):
        _translate = QtCore.QCoreApplication.translate
        propertyDialog.setWindowTitle(_translate("propertyDialog", "属性"))
        self.groupBox.setTitle(_translate("propertyDialog", "列标题设置"))
        self.groupBox_2.setTitle(_translate("propertyDialog", "其他设置"))
        self.Labelrowcount.setText(_translate("propertyDialog", "行数"))
        self.Labelcolcount.setText(_translate("propertyDialog", "列数"))
